// CREATE ABOUT MESSAGE
export const ABOUT_MESSAGE_REQUEST = "ABOUT_MESSAGE_REQUEST";
export const ABOUT_MESSAGE_SUCCESS = "ABOUT_MESSAGE_SUCCESS";
export const ABOUT_MESSAGE_FAIL = "ABOUT_MESSAGE_FAIL";
export const ABOUT_MESSAGE_RESET = "ABOUT_MESSAGE_RESET";
// GET ABOUT MESSAGE
export const ALL_ABOUT_MESSAGE_REQUEST = "ALL_ABOUT_MESSAGE_REQUEST";
export const ALL_ABOUT_MESSAGE_SUCCESS = "ALL_ABOUT_MESSAGE_SUCCESS";
export const ALL_ABOUT_MESSAGE_FAIL = "ALL_ABOUT_MESSAGE_FAIL";
// UPDATE ABOUT MESSAGE
export const UPDATE_ABOUT_MESSAGE_REQUEST = "UPDATE_ABOUT_MESSAGE_REQUEST";
export const UPDATE_ABOUT_MESSAGE_SUCCESS = "UPDATE_ABOUT_MESSAGE_SUCCESS";
export const UPDATE_ABOUT_MESSAGE_FAIL = "UPDATE_ABOUT_MESSAGE_FAIL";
export const UPDATE_ABOUT_MESSAGE_RESET = "UPDATE_ABOUT_MESSAGE_RESET";
// UPDATE ABOUT MESSAGE
export const DELETE_ABOUT_MESSAGE_REQUEST = "DELETE_ABOUT_MESSAGE_REQUEST";
export const DELETE_ABOUT_MESSAGE_SUCCESS = "DELETE_ABOUT_MESSAGE_SUCCESS";
export const DELETE_ABOUT_MESSAGE_FAIL = "DELETE_ABOUT_MESSAGE_FAIL";
export const DELETE_ABOUT_MESSAGE_RESET = "DELETE_ABOUT_MESSAGE_RESET";
// GET CONTENT DETAIL
export const CONTENT_DETAILS_REQUEST = "CONTENT_DETAILS_REQUEST";
export const CONTENT_DETAILS_SUCCESS = "CONTENT_DETAILS_SUCCESS";
export const CONTENT_DETAILS_FAIL = "CONTENT_DETAILS_FAIL";
// CLEAR ERRORS
export const CLEAR_ERRORS = "CLEAR_ERRORS";
