// CREATE BANNER
export const CREATE_BANNER_REQUEST = "CREATE_BANNER_REQUEST";
export const CREATE_BANNER_SUCCESS = "CREATE_BANNER_SUCCESS";
export const CREATE_BANNER_FAIL = "CREATE_BANNER_FAIL";
export const CREATE_BANNER_RESET = "CREATE_BANNER_RESET";
// GET BANNER
export const GET_BANNER_REQUEST = "GET_BANNER_REQUEST";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_FAIL = "GET_BANNER_FAIL";
// UPDATE BANNER
export const UPDATE_BANNER_REQUEST = "UPDATE_BANNER_REQUEST";
export const UPDATE_BANNER_SUCCESS = "UPDATE_BANNER_SUCCESS";
export const UPDATE_BANNER_FAIL = "UPDATE_BANNER_FAIL";
export const UPDATE_BANNER_RESET = "UPDATE_BANNER_RESET";
// DELETE BANNER
export const DELETE_BANNER_REQUEST = "DELETE_BANNER_REQUEST";
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS";
export const DELETE_BANNER_FAIL = "DELETE_BANNER_FAIL";
export const DELETE_BANNER_RESET = "DELETE_BANNER_RESET";
// DETAIL BANNER
export const DETAIL_BANNER_REQUEST = "DETAIL_BANNER_REQUEST";
export const DETAIL_BANNER_SUCCESS = "DETAIL_BANNER_SUCCESS";
export const DETAIL_BANNER_FAIL = "DETAIL_BANNER_FAIL";
// CLEAR ERRORS
export const CLEAR_ERRORS = "CLEAR_ERRORS";
