// NEW MESSAGE
export const NEW_MESSAGE_REQUEST = "NEW_MESSAGE_REQUEST";
export const NEW_MESSAGE_SUCCESS = "NEW_MESSAGE_SUCCESS";
export const NEW_MESSAGE_ERROR = "NEW_MESSAGE_ERROR";
export const NEW_MESSAGE_RESET = "NEW_MESSAGE_RESET";
// GET ALL MESSAGES
export const ALL_MESSAGE_REQUEST = "ALL_MESSAGE_REQUEST";
export const ALL_MESSAGE_SUCCESS = "ALL_MESSAGE_SUCCESS";
export const ALL_MESSAGE_ERROR = "ALL_MESSAGE_ERROR";
// DELETE MESSAGE
export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_ERROR = "DELETE_MESSAGE_ERROR";
export const DELETE_MESSAGE_RESET = "DELETE_MESSAGE_RESET";
// clear errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";
