// CREATE DATABASE
export const CREATE_DATABASE_REQUEST = "CREATE_DATABASE_REQUEST";
export const CREATE_DATABASE_SUCCESS = "CREATE_DATABASE_SUCCESS";
export const CREATE_DATABASE_FAIL = "CREATE_DATABASE_FAIL";
export const CREATE_DATABASE_RESET = "CREATE_DATABASE_RESET";
// GET DATABASE
export const GET_DATABASE_REQUEST = "GET_DATABASE_REQUEST";
export const GET_DATABASE_SUCCESS = "GET_DATABASE_SUCCESS";
export const GET_DATABASE_FAIL = "GET_DATABASE_FAIL";
// UPDATE DATABASE
export const UPDATE_DATABASE_REQUEST = "UPDATE_DATABASE_REQUEST";
export const UPDATE_DATABASE_SUCCESS = "UPDATE_DATABASE_SUCCESS";
export const UPDATE_DATABASE_FAIL = "UPDATE_DATABASE_FAIL";
export const UPDATE_DATABASE_RESET = "UPDATE_DATABASE_RESET";
// DELETE DATABASE
export const DELETE_DATABASE_REQUEST = "DELETE_DATABASE_REQUEST";
export const DELETE_DATABASE_SUCCESS = "DELETE_DATABASE_SUCCESS";
export const DELETE_DATABASE_FAIL = "DELETE_DATABASE_FAIL";
export const DELETE_DATABASE_RESET = "DELETE_DATABASE_RESET";
// DETAIL DATABASE
export const DETAIL_DATABASE_REQUEST = "DETAIL_DATABASE_REQUEST";
export const DETAIL_DATABASE_SUCCESS = "DETAIL_DATABASE_SUCCESS";
export const DETAIL_DATABASE_FAIL = "DETAIL_DATABASE_FAIL";
// CLEAR ERRORS
export const CLEAR_ERRORS = "CLEAR_ERRORS";
