// CREATE FAQ
export const CREATE_FAQ_REQUEST = "CREATE_FAQ_REQUEST";
export const CREATE_FAQ_SUCCESS = "CREATE_FAQ_SUCCESS";
export const CREATE_FAQ_FAIL = "CREATE_FAQ_FAIL";
export const CREATE_FAQ_RESET = "CREATE_FAQ_RESET";
// GET FAQ
export const GET_FAQ_REQUEST = "GET_FAQ_REQUEST";
export const GET_FAQ_SUCCESS = "GET_FAQ_SUCCESS";
export const GET_FAQ_FAIL = "GET_FAQ_FAIL";
// UPDATE FAQ
export const UPDATE_FAQ_REQUEST = "UPDATE_FAQ_REQUEST";
export const UPDATE_FAQ_SUCCESS = "UPDATE_FAQ_SUCCESS";
export const UPDATE_FAQ_FAIL = "UPDATE_FAQ_FAIL";
export const UPDATE_FAQ_RESET = "UPDATE_FAQ_RESET";
// DELETE FAQ
export const DELETE_FAQ_REQUEST = "DELETE_FAQ_REQUEST";
export const DELETE_FAQ_SUCCESS = "DELETE_FAQ_SUCCESS";
export const DELETE_FAQ_FAIL = "DELETE_FAQ_FAIL";
export const DELETE_FAQ_RESET = "DELETE_FAQ_RESET";
// DETAIL FAQ
export const DETAIL_FAQ_REQUEST = "DETAIL_FAQ_REQUEST";
export const DETAIL_FAQ_SUCCESS = "DETAIL_FAQ_SUCCESS";
export const DETAIL_FAQ_FAIL = "DETAIL_FAQ_FAIL";
// CLEAR ERRORS
export const CLEAR_ERRORS = "CLEAR_ERRORS";
