// CREATE FEATURE
export const CREATE_FEATURE_REQUEST = "CREATE_FEATURE_REQUEST";
export const CREATE_FEATURE_SUCCESS = "CREATE_FEATURE_SUCCESS";
export const CREATE_FEATURE_FAIL = "CREATE_FEATURE_FAIL";
export const CREATE_FEATURE_RESET = "CREATE_FEATURE_RESET";
// GET FEATURE
export const GET_FEATURE_REQUEST = "GET_FEATURE_REQUEST";
export const GET_FEATURE_SUCCESS = "GET_FEATURE_SUCCESS";
export const GET_FEATURE_FAIL = "GET_FEATURE_FAIL";
// UPDATE FEATURE
export const UPDATE_FEATURE_REQUEST = "UPDATE_FEATURE_REQUEST";
export const UPDATE_FEATURE_SUCCESS = "UPDATE_FEATURE_SUCCESS";
export const UPDATE_FEATURE_FAIL = "UPDATE_FEATURE_FAIL";
export const UPDATE_FEATURE_RESET = "UPDATE_FEATURE_RESET";
// DELETE FEATURE
export const DELETE_FEATURE_REQUEST = "DELETE_FEATURE_REQUEST";
export const DELETE_FEATURE_SUCCESS = "DELETE_FEATURE_SUCCESS";
export const DELETE_FEATURE_FAIL = "DELETE_FEATURE_FAIL";
export const DELETE_FEATURE_RESET = "DELETE_FEATURE_RESET";
// DETAIL FEATURE
export const DETAIL_FEATURE_REQUEST = "DETAIL_FEATURE_REQUEST";
export const DETAIL_FEATURE_SUCCESS = "DETAIL_FEATURE_SUCCESS";
export const DETAIL_FEATURE_FAIL = "DETAIL_FEATURE_FAIL";
// CLEAR ERRORS
export const CLEAR_ERRORS = "CLEAR_ERRORS";
