// CREATE MIGRATION
export const CREATE_MIGRATION_REQUEST = "CREATE_MIGRATION_REQUEST";
export const CREATE_MIGRATION_SUCCESS = "CREATE_MIGRATION_SUCCESS";
export const CREATE_MIGRATION_FAIL = "CREATE_MIGRATION_FAIL";
export const CREATE_MIGRATION_RESET = "CREATE_MIGRATION_RESET";
// GET MIGRATION
export const GET_MIGRATION_REQUEST = "GET_MIGRATION_REQUEST";
export const GET_MIGRATION_SUCCESS = "GET_MIGRATION_SUCCESS";
export const GET_MIGRATION_FAIL = "GET_MIGRATION_FAIL";
// UPDATE MIGRATION
export const UPDATE_MIGRATION_REQUEST = "UPDATE_MIGRATION_REQUEST";
export const UPDATE_MIGRATION_SUCCESS = "UPDATE_MIGRATION_SUCCESS";
export const UPDATE_MIGRATION_FAIL = "UPDATE_MIGRATION_FAIL";
export const UPDATE_MIGRATION_RESET = "UPDATE_MIGRATION_RESET";
// DELETE MIGRATION
export const DELETE_MIGRATION_REQUEST = "DELETE_MIGRATION_REQUEST";
export const DELETE_MIGRATION_SUCCESS = "DELETE_MIGRATION_SUCCESS";
export const DELETE_MIGRATION_FAIL = "DELETE_MIGRATION_FAIL";
export const DELETE_MIGRATION_RESET = "DELETE_MIGRATION_RESET";
// DETAIL MIGRATION
export const DETAIL_MIGRATION_REQUEST = "DETAIL_MIGRATION_REQUEST";
export const DETAIL_MIGRATION_SUCCESS = "DETAIL_MIGRATION_SUCCESS";
export const DETAIL_MIGRATION_FAIL = "DETAIL_MIGRATION_FAIL";
// CLEAR ERRORS
export const CLEAR_ERRORS = "CLEAR_ERRORS";
