// GET ALL PROJECTS
export const ALL_PROJECT_REQUEST = "ALL_PROJECT_REQUEST";
export const ALL_PROJECT_SUCCESS = "ALL_PROJECT_SUCCESS";
export const ALL_PROJECT_FAIL = "ALL_PROJECT_FAIL";

// GET ALL PROJECTS (ADMIN)
export const ALL_ADMIN_PROJECT_REQUEST = "ALL_ADMIN_PROJECT_REQUEST";
export const ALL_ADMIN_PROJECT_SUCCESS = "ALL_ADMIN_PROJECT_SUCCESS";
export const ALL_ADMIN_PROJECT_FAIL = "ALL_ADMIN_PROJECT_FAIL";

// CREATE NEW PROJECT (ADMIN)
export const NEW_PROJECT_REQUEST = "NEW_PROJECT_REQUEST";
export const NEW_PROJECT_SUCCESS = "NEW_PROJECT_SUCCESS";
export const NEW_PROJECT_FAIL = "NEW_PROJECT_FAIL";
export const NEW_PROJECT_RESET = "NEW_PROJECT_RESET";

// UPDATE PROJECT (ADMIN)
export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL";
export const UPDATE_PROJECT_RESET = "UPDATE_PROJECT_RESET";

// DELETE PROJECT (ADMIN)
export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";
export const DELETE_PROJECT_RESET = "DELETE_PROJECT_RESET";

// GET PROJECT DETAIL
export const PROJECT_DETAILS_REQUEST = "PROJECT_DETAILS_REQUEST";
export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS";
export const PROJECT_DETAILS_FAIL = "PROJECT_DETAILS_FAIL";

// CLEAR ERRORS
export const CLEAR_ERRORS = "CLEAR_ERRORS";
