// CREATE REASON
export const CREATE_REASON_REQUEST = "CREATE_REASON_REQUEST";
export const CREATE_REASON_SUCCESS = "CREATE_REASON_SUCCESS";
export const CREATE_REASON_FAIL = "CREATE_REASON_FAIL";
export const CREATE_REASON_RESET = "CREATE_REASON_RESET";
// GET REASON
export const GET_REASON_REQUEST = "GET_REASON_REQUEST";
export const GET_REASON_SUCCESS = "GET_REASON_SUCCESS";
export const GET_REASON_FAIL = "GET_REASON_FAIL";
// UPDATE REASON
export const UPDATE_REASON_REQUEST = "UPDATE_REASON_REQUEST";
export const UPDATE_REASON_SUCCESS = "UPDATE_REASON_SUCCESS";
export const UPDATE_REASON_FAIL = "UPDATE_REASON_FAIL";
export const UPDATE_REASON_RESET = "UPDATE_REASON_RESET";
// DELETE REASON
export const DELETE_REASON_REQUEST = "DELETE_REASON_REQUEST";
export const DELETE_REASON_SUCCESS = "DELETE_REASON_SUCCESS";
export const DELETE_REASON_FAIL = "DELETE_REASON_FAIL";
export const DELETE_REASON_RESET = "DELETE_REASON_RESET";
// DETAIL REASON
export const DETAIL_REASON_REQUEST = "DETAIL_REASON_REQUEST";
export const DETAIL_REASON_SUCCESS = "DETAIL_REASON_SUCCESS";
export const DETAIL_REASON_FAIL = "DETAIL_REASON_FAIL";
// CLEAR ERRORS
export const CLEAR_ERRORS = "CLEAR_ERRORS";
