// GET ALL REVIEWS
export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

// GET ALL REVIEWS (ADMIN)
export const ALL_ADMIN_REVIEW_REQUEST = "ALL_ADMIN_REVIEW_REQUEST";
export const ALL_ADMIN_REVIEW_SUCCESS = "ALL_ADMIN_REVIEW_SUCCESS";
export const ALL_ADMIN_REVIEW_FAIL = "ALL_ADMIN_REVIEW_FAIL";

// CREATE NEW REVIEW (ADMIN)
export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";

// UPDATE REVIEW (ADMIN)
export const UPDATE_REVIEW_REQUEST = "UPDATE_REVIEW_REQUEST";
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";
export const UPDATE_REVIEW_FAIL = "UPDATE_REVIEW_FAIL";
export const UPDATE_REVIEW_RESET = "UPDATE_REVIEW_RESET";

// DELETE REVIEW (ADMIN)
export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";

// GET REVIEW DETAIL
export const REVIEW_DETAILS_REQUEST = "REVIEW_DETAILS_REQUEST";
export const REVIEW_DETAILS_SUCCESS = "REVIEW_DETAILS_SUCCESS";
export const REVIEW_DETAILS_FAIL = "REVIEW_DETAILS_FAIL";

// CLEAR ERRORS
export const CLEAR_ERRORS = "CLEAR_ERRORS";
