// CREATE SKILL
export const CREATE_SKILL_REQUEST = "CREATE_SKILL_REQUEST";
export const CREATE_SKILL_SUCCESS = "CREATE_SKILL_SUCCESS";
export const CREATE_SKILL_FAIL = "CREATE_SKILL_FAIL";
export const CREATE_SKILL_RESET = "CREATE_SKILL_RESET";
// GET SKILL
export const GET_SKILL_REQUEST = "GET_SKILL_REQUEST";
export const GET_SKILL_SUCCESS = "GET_SKILL_SUCCESS";
export const GET_SKILL_FAIL = "GET_SKILL_FAIL";
// UPDATE SKILL
export const UPDATE_SKILL_REQUEST = "UPDATE_SKILL_REQUEST";
export const UPDATE_SKILL_SUCCESS = "UPDATE_SKILL_SUCCESS";
export const UPDATE_SKILL_FAIL = "UPDATE_SKILL_FAIL";
export const UPDATE_SKILL_RESET = "UPDATE_SKILL_RESET";
// DELETE SKILL
export const DELETE_SKILL_REQUEST = "DELETE_SKILL_REQUEST";
export const DELETE_SKILL_SUCCESS = "DELETE_SKILL_SUCCESS";
export const DELETE_SKILL_FAIL = "DELETE_SKILL_FAIL";
export const DELETE_SKILL_RESET = "DELETE_SKILL_RESET";
// DETAIL SKILL
export const DETAIL_SKILL_REQUEST = "DETAIL_SKILL_REQUEST";
export const DETAIL_SKILL_SUCCESS = "DETAIL_SKILL_SUCCESS";
export const DETAIL_SKILL_FAIL = "DETAIL_SKILL_FAIL";
// CLEAR ERRORS
export const CLEAR_ERRORS = "CLEAR_ERRORS";
