// CREATE TECH CONTENT
export const CREATE_TECH_CONTENT_REQUEST = "CREATE_TECH_CONTENT_REQUEST";
export const CREATE_TECH_CONTENT_SUCCESS = "CREATE_TECH_CONTENT_SUCCESS";
export const CREATE_TECH_CONTENT_FAIL = "CREATE_TECH_CONTENT_FAIL";
export const CREATE_TECH_CONTENT_RESET = "CREATE_TECH_CONTENT_RESET";
// GET TECH CONTENT
export const GET_TECH_CONTENT_REQUEST = "GET_TECH_CONTENT_REQUEST";
export const GET_TECH_CONTENT_SUCCESS = "GET_TECH_CONTENT_SUCCESS";
export const GET_TECH_CONTENT_FAIL = "GET_TECH_CONTENT_FAIL";
// UPDATE TECH CONTENT
export const UPDATE_TECH_CONTENT_REQUEST = "UPDATE_TECH_CONTENT_REQUEST";
export const UPDATE_TECH_CONTENT_SUCCESS = "UPDATE_TECH_CONTENT_SUCCESS";
export const UPDATE_TECH_CONTENT_FAIL = "UPDATE_TECH_CONTENT_FAIL";
export const UPDATE_TECH_CONTENT_RESET = "UPDATE_TECH_CONTENT_RESET";
// UPDATE TECH CONTENT
export const DELETE_TECH_CONTENT_REQUEST = "DELETE_TECH_CONTENT_REQUEST";
export const DELETE_TECH_CONTENT_SUCCESS = "DELETE_TECH_CONTENT_SUCCESS";
export const DELETE_TECH_CONTENT_FAIL = "DELETE_TECH_CONTENT_FAIL";
export const DELETE_TECH_CONTENT_RESET = "DELETE_TECH_CONTENT_RESET";
// DETAIL TECH CONTENT
export const DETAIL_TECH_CONTENT_REQUEST = "DETAIL_TECH_CONTENT_REQUEST";
export const DETAIL_TECH_CONTENT_SUCCESS = "DETAIL_TECH_CONTENT_SUCCESS";
export const DETAIL_TECH_CONTENT_FAIL = "DETAIL_TECH_CONTENT_FAIL";
// CLEAR ERRORS
export const CLEAR_ERRORS = "CLEAR_ERRORS";
