// CREATE WEB
export const CREATE_WEB_REQUEST = "CREATE_WEB_REQUEST";
export const CREATE_WEB_SUCCESS = "CREATE_WEB_SUCCESS";
export const CREATE_WEB_FAIL = "CREATE_WEB_FAIL";
export const CREATE_WEB_RESET = "CREATE_WEB_RESET";
// GET WEB
export const GET_WEB_REQUEST = "GET_WEB_REQUEST";
export const GET_WEB_SUCCESS = "GET_WEB_SUCCESS";
export const GET_WEB_FAIL = "GET_WEB_FAIL";
// UPDATE WEB
export const UPDATE_WEB_REQUEST = "UPDATE_WEB_REQUEST";
export const UPDATE_WEB_SUCCESS = "UPDATE_WEB_SUCCESS";
export const UPDATE_WEB_FAIL = "UPDATE_WEB_FAIL";
export const UPDATE_WEB_RESET = "UPDATE_WEB_RESET";
// DELETE WEB
export const DELETE_WEB_REQUEST = "DELETE_WEB_REQUEST";
export const DELETE_WEB_SUCCESS = "DELETE_WEB_SUCCESS";
export const DELETE_WEB_FAIL = "DELETE_WEB_FAIL";
export const DELETE_WEB_RESET = "DELETE_WEB_RESET";
// DETAIL WEB
export const DETAIL_WEB_REQUEST = "DETAIL_WEB_REQUEST";
export const DETAIL_WEB_SUCCESS = "DETAIL_WEB_SUCCESS";
export const DETAIL_WEB_FAIL = "DETAIL_WEB_FAIL";
// CLEAR ERRORS
export const CLEAR_ERRORS = "CLEAR_ERRORS";
